#!/usr/bin/env bash
# Script displays numbers from 1 to 100
# Displays FizzBuzz when number is multiple of 3 and 5
# Displays Fizz when number is a multiple of 3
# Displays Buzz when number is a multiple of 5

for ((i=1; i<=100; i++))
do
	if (( i % 15 == 0 )); then
		echo "FizzBuzz"
	elif (( i % 3 == 0 )); then
		echo "Fizz"
	elif (( i % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
