#!/usr/bin/env bash
# Script displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

command=$(ls)
for FILE in $command
do
	echo "$FILE" | cut -d "-" -f2
done
 
